[profile.default]
src = "src"
out = "artifacts"
libs = ["node_modules"]
remappings = [
    "@chainlink/=node_modules/@chainlink/",
    "@eth-optimism/=node_modules/@hyperlane-xyz/core/node_modules/@eth-optimism/",
    "@hyperlane-xyz/=node_modules/@hyperlane-xyz/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "forge-std/=node_modules/forge-std/",
    "hardhat/=node_modules/hardhat/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
